name: 'Issue Opened/Edited'
on:
  issues:
    types: [opened, edited]
jobs:
  show-details:
    runs-on: ubuntu-latest
    steps:
      - name: 'Details'
        run: echo '${{ github.event.issues }}'
